#!/usr/bin/env python3
"""Generate code from the sheets. Every row becomes one piece of code built from its columns.

  python3 tools/gen.py

GTA side (C++17, gta/src/gen/):        natives.hpp, xmap.hpp, protocol.hpp, settings.hpp, keys.hpp,
                                       controls.hpp, obstacles.hpp, player_proxies.hpp, garages.hpp
BeamNG side (Lua, .../beamls/gen/):    protocol.lua, settings.lua, bngapi.lua, obstacles.lua,
                                       traffic_proxies.lua, keys.lua
BeamNG data:                           core/input/actions/beamls.json, vehicles/beamls_proxy/*.pc
Docs:                                  CREDITS.md

Never edit generated files by hand: change the sheet and run this again.
"""
import hashlib
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEETS = os.path.join(ROOT, "sheets")
GTA_GEN = os.path.join(ROOT, "gta", "src", "gen")
BNG_MOD = os.path.join(ROOT, "beamng", "mod")
BNG_GEN = os.path.join(BNG_MOD, "lua", "ge", "extensions", "beamls", "gen")
HEADER_CPP = "// GENERATED by tools/gen.py from sheets/{sheet}.json. Do not edit; change the sheet.\n"
HEADER_LUA = "-- GENERATED by tools/gen.py from sheets/{sheet}.json. Do not edit; change the sheet.\n"


def load(name):
    with open(os.path.join(SHEETS, name + ".json"), encoding="utf-8") as f:
        return json.load(f)


def digest():
    h = hashlib.sha256()
    for name in sorted(os.listdir(SHEETS)):
        if name.endswith(".json"):
            with open(os.path.join(SHEETS, name), "rb") as f:
                h.update(name.encode())
                h.update(f.read())
    return h.hexdigest()


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def joaat(s):
    h = 0
    for c in s.lower().encode():
        h = (h + c) & 0xFFFFFFFF
        h = (h + (h << 10)) & 0xFFFFFFFF
        h ^= h >> 6
    h = (h + (h << 3)) & 0xFFFFFFFF
    h ^= h >> 11
    h = (h + (h << 15)) & 0xFFFFFFFF
    return h


def lua_str(s):
    return json.dumps(s)  # JSON string escapes are valid Lua string escapes for our content


def lua_val(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return lua_str(v)
    if isinstance(v, list):
        return "{" + ", ".join(lua_val(x) for x in v) + "}"
    if v is None:
        return "nil"
    raise TypeError(v)


# ---------------------------------------------------------------------------------------------
# GTA natives
# ---------------------------------------------------------------------------------------------
CPP_TYPES = {
    "void": "void", "BOOL": "BOOL", "int": "int", "float": "float", "Hash": "Hash", "Any": "Any",
    "Ped": "Ped", "Vehicle": "Vehicle", "Entity": "Entity", "Player": "Player", "Object": "Object",
    "Cam": "Cam", "Vector3": "Vector3", "const char*": "const char*", "char*": "const char*",
}


def cpp_type(t):
    t = t.strip()
    if t in CPP_TYPES:
        return CPP_TYPES[t]
    if t.endswith("*"):
        base = t[:-1].strip()
        if base in CPP_TYPES:
            return CPP_TYPES[base] + "*"
    raise ValueError(f"unknown native type {t}")


def gen_natives():
    sheet = load("natives")
    games = {g["id"]: g for g in load("games")["rows"]}
    builds = games["gta-v"]["supported_builds"]
    by_ns = {}
    for r in sheet["rows"]:
        by_ns.setdefault(r["ns"], []).append(r)
    out = [HEADER_CPP.format(sheet="natives"), "#pragma once\n#include \"../core/invoker.hpp\"\n\n"]
    out.append("// One wrapper per row of sheets/natives.json: original hash, translated per build by the invoker.\n")
    for ns in sorted(by_ns):
        out.append(f"namespace {ns}\n{{\n")
        for r in by_ns[ns]:
            ret = cpp_type(r["ret"])
            params = []
            names = []
            for p in r["params"]:
                t, n = p.rsplit(" ", 1)
                params.append(f"{cpp_type(t)} {n}")
                names.append(n)
            args = "".join(", " + n for n in names)
            body = f"beamls::invoke<{ret}>(0x{int(r['hash'], 16):016X}ull{args})"
            if ret == "void":
                out.append(f"\tinline void {r['id']}({', '.join(params)}) {{ {body}; }}\n")
            else:
                out.append(f"\tinline {ret} {r['id']}({', '.join(params)}) {{ return {body}; }}\n")
        out.append("}\n\n")
    write(os.path.join(GTA_GEN, "natives.hpp"), "".join(out))

    x = [HEADER_CPP.format(sheet="natives"), "#pragma once\n#include <cstddef>\n#include <cstdint>\n\nnamespace beamls::gen\n{\n"]
    x.append("\tstruct XmapEntry { std::uint64_t original; std::uint64_t translated; const char* name; };\n")
    x.append("\tstruct BuildTable { const char* build; const XmapEntry* entries; std::size_t count; };\n\n")
    for b in builds:
        x.append(f"\t// Build {b}: translated == 0 means the cell is still empty in the sheet; the build cannot run.\n")
        x.append(f"\tinline constexpr XmapEntry kXmap_{b}[] = {{\n")
        for r in sheet["rows"]:
            t = r["xmap"].get(b, "") or "0x0"
            x.append(f"\t\t{{0x{int(r['hash'], 16):016X}ull, 0x{int(t, 16):016X}ull, \"{r['id']}\"}},\n")
        x.append("\t};\n\n")
    x.append("\tinline constexpr BuildTable kBuildTables[] = {\n")
    for b in builds:
        x.append(f"\t\t{{\"{b}\", kXmap_{b}, sizeof(kXmap_{b}) / sizeof(kXmap_{b}[0])}},\n")
    x.append("\t};\n}\n")
    write(os.path.join(GTA_GEN, "xmap.hpp"), "".join(x))


# ---------------------------------------------------------------------------------------------
# Protocol
# ---------------------------------------------------------------------------------------------
CPP_FIELD = {"f32": "float", "i32": "std::int32_t", "u32": "std::uint32_t", "bool": "bool", "str": "std::string",
             "f32[]": "std::vector<float>"}
CPP_DEFAULT = {"f32": " = 0.0f", "i32": " = 0", "u32": " = 0", "bool": " = false", "str": "", "f32[]": ""}


def camel(s):
    return "".join(p.capitalize() for p in s.split("_"))


def cpp_encode_scalar(name, typ, expr):
    if typ == "f32":
        return f"w.num(\"{name}\", {expr});"
    if typ in ("i32", "u32"):
        return f"w.integer(\"{name}\", static_cast<long long>({expr}));"
    if typ == "bool":
        return f"w.boolean(\"{name}\", {expr});"
    if typ == "str":
        return f"w.str(\"{name}\", {expr});"
    if typ == "f32[]":
        return f"w.floats(\"{name}\", {expr});"
    raise ValueError(typ)


def cpp_decode_scalar(typ, src, dst):
    if typ == "f32":
        return f"{dst} = static_cast<float>({src}.num());"
    if typ == "i32":
        return f"{dst} = static_cast<std::int32_t>({src}.num());"
    if typ == "u32":
        return f"{dst} = static_cast<std::uint32_t>({src}.num());"
    if typ == "bool":
        return f"{dst} = {src}.boolean();"
    if typ == "str":
        return f"{dst} = {src}.str();"
    if typ == "f32[]":
        return f"{dst}.clear(); for (const auto& e : {src}.arr()) {dst}.push_back(static_cast<float>(e.num()));"
    raise ValueError(typ)


def gen_protocol():
    sheet = load("messages")
    proto = sheet["proto"]
    o = [HEADER_CPP.format(sheet="messages"), "#pragma once\n#include <cstdint>\n#include <string>\n#include <vector>\n#include \"../core/json.hpp\"\n\n"]
    o.append("namespace beamls::msg\n{\n")
    o.append(f"\tinline constexpr int kProto = {proto};\n\n")
    for m in sheet["rows"]:
        cname = camel(m["id"])
        o.append(f"\t// {m['id']} ({m['dir']}, {m['rate']}): {m['purpose']}\n")
        o.append(f"\tstruct {cname}\n\t{{\n\t\tstatic constexpr const char* kType = \"{m['id']}\";\n")
        for f in m["fields"]:
            name, typ = f[0], f[1]
            if typ == "rec[]":
                rname = camel(name.rstrip("s")) if name.endswith("s") else camel(name) + "Rec"
                o.append(f"\t\tstruct {rname}\n\t\t{{\n")
                for rf in f[3]:
                    o.append(f"\t\t\t{CPP_FIELD[rf[1]]} {rf[0]}{CPP_DEFAULT[rf[1]]}; // {rf[2]}\n")
                o.append("\t\t};\n")
                o.append(f"\t\tstd::vector<{rname}> {name}; // {f[2]}\n")
            else:
                o.append(f"\t\t{CPP_FIELD[typ]} {name}{CPP_DEFAULT[typ]}; // {f[2]}\n")
        # encode
        o.append("\n\t\tstd::string encode() const\n\t\t{\n\t\t\tjson::Writer w;\n\t\t\tw.begin();\n\t\t\tw.str(\"t\", kType);\n")
        for f in m["fields"]:
            name, typ = f[0], f[1]
            if typ == "rec[]":
                o.append(f"\t\t\tw.beginArray(\"{name}\");\n\t\t\tfor (const auto& r : {name})\n\t\t\t{{\n\t\t\t\tw.beginRow();\n")
                for rf in f[3]:
                    if rf[1] == "f32":
                        o.append(f"\t\t\t\tw.rowNum(r.{rf[0]});\n")
                    elif rf[1] in ("i32", "u32"):
                        o.append(f"\t\t\t\tw.rowInt(static_cast<long long>(r.{rf[0]}));\n")
                    else:
                        raise ValueError("rec fields must be numeric")
                o.append("\t\t\t\tw.endRow();\n\t\t\t}\n\t\t\tw.endArray();\n")
            else:
                o.append(f"\t\t\t{cpp_encode_scalar(name, typ, name)}\n")
        o.append("\t\t\tw.end();\n\t\t\treturn w.take();\n\t\t}\n")
        # decode
        o.append("\n\t\tbool decode(const json::Value& v)\n\t\t{\n\t\t\tif (!v.isObject()) return false;\n")
        for f in m["fields"]:
            name, typ = f[0], f[1]
            if typ == "rec[]":
                o.append(f"\t\t\t{name}.clear();\n\t\t\tif (const json::Value* a = v.get(\"{name}\"))\n\t\t\t{{\n\t\t\t\tfor (const auto& row : a->arr())\n\t\t\t\t{{\n")
                o.append(f"\t\t\t\t\tconst auto& c = row.arr();\n\t\t\t\t\tif (c.size() < {len(f[3])}) continue;\n\t\t\t\t\t{name}.emplace_back();\n\t\t\t\t\tauto& r = {name}.back();\n")
                for i, rf in enumerate(f[3]):
                    o.append(f"\t\t\t\t\t{cpp_decode_scalar(rf[1], f'c[{i}]', 'r.' + rf[0])}\n")
                o.append("\t\t\t\t}\n\t\t\t}\n")
            else:
                o.append(f"\t\t\tif (const json::Value* f = v.get(\"{name}\")) {{ {cpp_decode_scalar(typ, '(*f)', name)} }}\n")
        o.append("\t\t\treturn true;\n\t\t}\n\t};\n\n")
    o.append("}\n")
    write(os.path.join(GTA_GEN, "protocol.hpp"), "".join(o))

    L = [HEADER_LUA.format(sheet="messages"), "local M = {}\n", f"M.proto = {proto}\nM.encode = {{}}\nM.decode = {{}}\nM.dir = {{}}\n\n"]
    for m in sheet["rows"]:
        L.append(f"-- {m['id']} ({m['dir']}): {m['purpose']}\nM.dir[{lua_str(m['id'])}] = {lua_str(m['dir'])}\n")
        L.append(f"M.encode[{lua_str(m['id'])}] = function(m)\n  local o = {{t = {lua_str(m['id'])}}}\n")
        for f in m["fields"]:
            name, typ = f[0], f[1]
            if typ == "rec[]":
                L.append(f"  o.{name} = {{}}\n  for i, r in ipairs(m.{name} or {{}}) do\n    o.{name}[i] = {{")
                L.append(", ".join(f"r.{rf[0]} or 0" for rf in f[3]))
                L.append("}\n  end\n")
            elif typ == "f32[]":
                L.append(f"  o.{name} = m.{name} or {{}}\n")
            elif typ == "bool":
                L.append(f"  o.{name} = m.{name} and true or false\n")
            elif typ == "str":
                L.append(f"  o.{name} = tostring(m.{name} or '')\n")
            else:
                L.append(f"  o.{name} = tonumber(m.{name}) or 0\n")
        L.append("  return o\nend\n")
        L.append(f"M.decode[{lua_str(m['id'])}] = function(o)\n  local m = {{t = {lua_str(m['id'])}}}\n")
        for f in m["fields"]:
            name, typ = f[0], f[1]
            if typ == "rec[]":
                L.append(f"  m.{name} = {{}}\n  for i, c in ipairs(o.{name} or {{}}) do\n    m.{name}[i] = {{")
                L.append(", ".join(f"{rf[0]} = c[{i + 1}]" for i, rf in enumerate(f[3])))
                L.append("}\n  end\n")
            elif typ == "f32[]":
                L.append(f"  m.{name} = o.{name} or {{}}\n")
            elif typ == "bool":
                L.append(f"  m.{name} = o.{name} == true\n")
            elif typ == "str":
                L.append(f"  m.{name} = o.{name} and tostring(o.{name}) or ''\n")
            else:
                L.append(f"  m.{name} = tonumber(o.{name}) or 0\n")
        L.append("  return m\nend\n\n")
    L.append("return M\n")
    write(os.path.join(BNG_GEN, "protocol.lua"), "".join(L))


# ---------------------------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------------------------
def cpp_const(name, v):
    if isinstance(v, bool):
        return f"\tinline constexpr bool {name} = {'true' if v else 'false'};\n"
    if isinstance(v, int):
        return f"\tinline constexpr int {name} = {v};\n"
    if isinstance(v, float):
        return f"\tinline constexpr float {name} = {v!r}f;\n"
    if isinstance(v, str):
        return f"\tinline constexpr const char* {name} = {json.dumps(v)};\n"
    if isinstance(v, list):
        if all(isinstance(x, str) for x in v):
            items = ", ".join(json.dumps(x) for x in v)
            return f"\tinline constexpr const char* {name}[] = {{{items}}};\n"
        if all(isinstance(x, int) and not isinstance(x, bool) for x in v):
            return f"\tinline constexpr int {name}[] = {{{', '.join(str(x) for x in v)}}};\n"
        return f"\tinline constexpr float {name}[] = {{{', '.join(repr(float(x)) + 'f' for x in v)}}};\n"
    raise TypeError(v)


def gen_settings():
    sheet = load("settings")
    c = [HEADER_CPP.format(sheet="settings"), "#pragma once\n\nnamespace beamls::settings\n{\n"]
    L = [HEADER_LUA.format(sheet="settings"), "local M = {}\n"]
    for r in sheet["rows"]:
        if r["side"] in ("gta", "both"):
            c.append(f"\t// {r['meaning']} ({r['unit']})\n" + cpp_const(r["id"], r["value"]))
        if r["side"] in ("beamng", "both"):
            L.append(f"-- {r['meaning']} ({r['unit']})\nM.{r['id']} = {lua_val(r['value'])}\n")
    c.append("}\n")
    L.append("return M\n")
    write(os.path.join(GTA_GEN, "settings.hpp"), "".join(c))
    write(os.path.join(BNG_GEN, "settings.lua"), "".join(L))


# ---------------------------------------------------------------------------------------------
# BeamNG API wrappers
# ---------------------------------------------------------------------------------------------
def gen_bngapi():
    sheet = load("bng_api")
    L = [HEADER_LUA.format(sheet="bng_api"), """-- Each row is one wrapper. GE rows run in pcall; the first failure of each row is logged as
-- 'bngapi FAIL <id>' and the row's fallback is returned. Vehicle rows (M.ve.*) return a code string
-- for veh:queueLuaCommand that runs the body in pcall inside the vehicle VM.
local M = {}
M.ve = {}
M.failed = {}
M.ok = {}

local function logFail(id, err)
  if not M.failed[id] then
    M.failed[id] = tostring(err)
    if log then log('E', 'beamls.bngapi', 'bngapi FAIL ' .. id .. ': ' .. tostring(err)) end
  end
end

local function ser(v)
  local t = type(v)
  if t == 'number' then return string.format('%.17g', v) end
  if t == 'boolean' then return v and 'true' or 'false' end
  if t == 'nil' then return 'nil' end
  return string.format('%q', tostring(v))
end
M.ser = ser

function M.report()
  local ok, failed = {}, {}
  for id in pairs(M.ok) do ok[#ok + 1] = id end
  for id, err in pairs(M.failed) do failed[#failed + 1] = id .. ': ' .. err end
  table.sort(ok)
  table.sort(failed)
  return ok, failed
end

"""]
    for r in sheet["rows"]:
        args = r.get("args", [])
        arglist = ", ".join(args)
        body = "\n".join("    " + line for line in r["body"].split("\n"))
        L.append(f"-- {r['id']}: {r['purpose']} (source: {r['source']})\n")
        if r["vm"] == "ge":
            L.append(f"function M.{r['id']}({arglist})\n")
            L.append("  local res = {pcall(function()\n" + body + "\n  end)}\n")
            L.append(f"  if not res[1] then\n    logFail({lua_str(r['id'])}, res[2])\n    return {r['fallback']}\n  end\n")
            L.append(f"  M.ok[{lua_str(r['id'])}] = true\n  return unpack(res, 2, table.maxn(res))\nend\n\n")
        else:
            decl = "".join(f"'local {a} = ' .. ser({a}) .. '\\n' .. " for a in args)
            code = r["body"].replace("\\", "\\\\")
            L.append(f"function M.ve.{r['id']}({arglist})\n")
            L.append(f"  return 'local ok, err = pcall(function()\\n' .. {decl}{lua_str(code)} .. "
                     f"'\\nend)\\nif not ok then log(\"E\", \"beamls.ve\", \"bngapi FAIL {r['id']}: \" .. tostring(err)) end'\n")
            L.append("end\n\n")
    L.append("return M\n")
    write(os.path.join(BNG_GEN, "bngapi.lua"), "".join(L))


# ---------------------------------------------------------------------------------------------
# Small tables (keys, controls, obstacles, proxies, garages)
# ---------------------------------------------------------------------------------------------
def gen_tables():
    keys = load("keys")
    c = [HEADER_CPP.format(sheet="keys"), "#pragma once\n\nnamespace beamls::gen\n{\n"]
    c.append("\tenum class KeyAction { " + ", ".join(camel(k["id"]) for k in keys["rows"] if k["side"] == "gta") + " };\n")
    c.append("\tstruct KeyRow { KeyAction action; bool isVk; int code; const char* label; };\n")
    c.append("\tinline constexpr KeyRow kKeys[] = {\n")
    for k in keys["rows"]:
        if k["side"] != "gta":
            continue
        kind, val = k["input"].split(":")
        c.append(f"\t\t{{KeyAction::{camel(k['id'])}, {'true' if kind == 'vk' else 'false'}, {int(val, 0)}, {json.dumps(k['label'])}}}, // {k['action']}\n")
    c.append("\t};\n}\n")
    write(os.path.join(GTA_GEN, "keys.hpp"), "".join(c))

    L = [HEADER_LUA.format(sheet="keys"), "local M = {}\n"]
    actions = {}
    for k in keys["rows"]:
        L.append(f"M[{lua_str(k['id'])}] = {{side = {lua_str(k['side'])}, input = {lua_str(k['input'])}, label = {lua_str(k['label'])}}}\n")
        if k["side"] == "beamng":
            actions["beamls_" + k["id"]] = {
                "cat": "beamls", "order": len(actions), "ctx": "tlua",
                "onDown": f"if beamls_main then beamls_main.onKey({json.dumps(k['id'])}) end",
                "title": "BeamNG x Los Santos: " + k["label"], "desc": k["action"],
            }
    L.append("return M\n")
    write(os.path.join(BNG_GEN, "keys.lua"), "".join(L))
    write(os.path.join(BNG_MOD, "lua", "ge", "extensions", "core", "input", "actions", "beamls.json"),
          json.dumps(actions, indent=2) + "\n")

    ctl = load("controls")
    c = [HEADER_CPP.format(sheet="controls"), "#pragma once\n\nnamespace beamls::gen\n{\n"]
    c.append("\tenum class ControlKind { Axis, Button, Press };\n")
    c.append("\tenum class InputField { None, " + ", ".join(sorted({camel(r['field']) for r in ctl['rows'] if r['field'] != 'none'})) + " };\n")
    c.append("\tstruct ControlRow { int control; const char* name; ControlKind kind; InputField field; float scale; };\n")
    c.append("\tinline constexpr ControlRow kControls[] = {\n")
    for r in ctl["rows"]:
        field = "None" if r["field"] == "none" else camel(r["field"])
        c.append(f"\t\t{{{r['gta_control']}, \"{r['gta_name']}\", ControlKind::{camel(r['kind'])}, InputField::{field}, {float(r['scale'])!r}f}},\n")
    c.append("\t};\n}\n")
    write(os.path.join(GTA_GEN, "controls.hpp"), "".join(c))

    obs = load("obstacles")
    c = [HEADER_CPP.format(sheet="obstacles"), "#pragma once\n\nnamespace beamls::gen\n{\n"]
    c.append("\tstruct ObstacleRow { int id; const char* name; const char* bngKind; float width; float thickness; float height; int maxCount; int lifetimeMs; };\n")
    c.append("\tinline constexpr ObstacleRow kObstacles[] = {\n")
    for r in obs["rows"]:
        c.append(f"\t\t{{{r['id']}, \"{r['name']}\", \"{r['bng_kind']}\", {float(r['width'])!r}f, {float(r['thickness'])!r}f, {float(r['height'])!r}f, {r['max_count']}, {r['lifetime_ms']}}},\n")
    c.append("\t};\n")
    for r in obs["rows"]:
        c.append(f"\tinline constexpr int kObstacle{camel(r['name'])} = {r['id']};\n")
    c.append("}\n")
    write(os.path.join(GTA_GEN, "obstacles.hpp"), "".join(c))
    L = [HEADER_LUA.format(sheet="obstacles"), "local M = {}\n"]
    for r in obs["rows"]:
        L.append(f"M[{r['id']}] = {{name = {lua_str(r['name'])}, kind = {lua_str(r['bng_kind'])}, shape = {lua_str(r['shape'])}, "
                 f"width = {r['width']}, thickness = {r['thickness']}, height = {r['height']}, maxCount = {r['max_count']}, lifetimeMs = {r['lifetime_ms']}}}\n")
        L.append(f"M.{r['name']} = {r['id']}\n")
    L.append("return M\n")
    write(os.path.join(BNG_GEN, "obstacles.lua"), "".join(L))

    pp = load("player_proxies")
    c = [HEADER_CPP.format(sheet="player_proxies"), "#pragma once\n#include <cstdint>\n\nnamespace beamls::gen\n{\n"]
    c.append("\tstruct PlayerProxyRow { const char* id; float minLength, maxLength, minHeight, maxHeight; const char* model; std::uint32_t modelHash; float gtaLength; };\n")
    c.append("\tinline constexpr PlayerProxyRow kPlayerProxies[] = {\n")
    for r in pp["rows"]:
        c.append(f"\t\t{{\"{r['id']}\", {float(r['min_length'])!r}f, {float(r['max_length'])!r}f, {float(r['min_height'])!r}f, {float(r['max_height'])!r}f, "
                 f"\"{r['gta_model']}\", 0x{joaat(r['gta_model']):08X}u, {float(r['gta_length'])!r}f}},\n")
    c.append("\t};\n}\n")
    write(os.path.join(GTA_GEN, "player_proxies.hpp"), "".join(c))

    tp = load("traffic_proxies")
    L = [HEADER_LUA.format(sheet="traffic_proxies"), "local M = {}\n"]
    for i, r in enumerate(tp["rows"], 1):
        L.append(f"M[{i}] = {{id = {lua_str(r['id'])}, maxLength = {r['max_length']}, maxHeight = {r['max_height']}, "
                 f"length = {r['length']}, width = {r['width']}, height = {r['height']}, mass = {r['mass_kg']}, "
                 f"config = {lua_str('vehicles/beamls_proxy/' + r['id'] + '.pc')}}}\n")
        pc = {"format": 2, "model": "beamls_proxy", "parts": {"beamls_proxy_body": "beamls_proxy_body"},
              "vars": {"$length": r["length"], "$width": r["width"], "$height": r["height"], "$mass": r["mass_kg"]}}
        write(os.path.join(BNG_MOD, "vehicles", "beamls_proxy", r["id"] + ".pc"), json.dumps(pc, indent=2) + "\n")
    L.append("return M\n")
    write(os.path.join(BNG_GEN, "traffic_proxies.lua"), "".join(L))

    gar = load("garages")
    c = [HEADER_CPP.format(sheet="garages"), "#pragma once\n\nnamespace beamls::gen\n{\n"]
    c.append("\tstruct GarageRow { const char* id; const char* name; float x, y, z, radius; int cost; };\n")
    c.append("\tinline constexpr GarageRow kGarages[] = {\n")
    for r in gar["rows"]:
        c.append(f"\t\t{{\"{r['id']}\", {json.dumps(r['name'])}, {float(r['x'])!r}f, {float(r['y'])!r}f, {float(r['z'])!r}f, {float(r['radius'])!r}f, {r['cost']}}},\n")
    c.append("\t};\n}\n")
    write(os.path.join(GTA_GEN, "garages.hpp"), "".join(c))


def gen_bng_assets():
    """beamls_proxy jbeam (rigid invisible box sized by .pc variables) and the slab unit cube."""
    tp = load("traffic_proxies")["rows"]
    settings = {r["id"]: r["value"] for r in load("settings")["rows"]}
    medium = next((r for r in tp if r["id"] == "medium"), tp[0])
    corners = {}
    for sx in (-1, 1):
        for sy in (-1, 1):
            for sz in (-1, 1):
                name = "c" + "".join("p" if s > 0 else "n" for s in (sx, sy, sz))
                corners[name] = (sx, sy, sz)

    def expr(axis, s):
        var = {"x": "$width", "y": "$length", "z": "$height"}[axis]
        return f"$={'' if s > 0 else '-'}{var}/2"

    nodes = [["id", "posX", "posY", "posZ"], {"nodeWeight": "$=$mass/12"}, {"collision": True},
             {"selfCollision": False}, {"frictionCoef": 0.6}, {"nodeMaterial": "|NM_METAL"}, {"group": "beamls_proxy"}]
    nodes.append(["p0", 0.0, 0.0, 0.0])
    nodes.append(["pb", 0.0, "$=$length/2", 0.0])   # back: BeamNG vehicles face -Y
    nodes.append(["pl", "$=$width/2", 0.0, 0.0])    # left: +X
    nodes.append(["pu", 0.0, 0.0, "$=$height/2"])
    for n, (sx, sy, sz) in corners.items():
        nodes.append([n, expr("x", sx), expr("y", sy), expr("z", sz)])
    names = [n[0] for n in nodes if isinstance(n, list) and n[0] != "id"]
    beams = [["id1:", "id2:"], {"beamSpring": 30000000, "beamDamp": 800}, {"beamDeform": "FLT_MAX", "beamStrength": "FLT_MAX"}]
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            beams.append([names[i], names[j]])
    # Box faces as outward-facing triangles (counter-clockwise seen from outside).
    tris = [["id1:", "id2:", "id3:"]]
    faces = []
    for axis in range(3):
        for s in (-1, 1):
            quad = [n for n, c in corners.items() if c[axis] == s]
            others = [a for a in range(3) if a != axis]
            # order the 4 corners around the face
            quad.sort(key=lambda n: __import__("math").atan2(corners[n][others[1]], corners[n][others[0]]))
            normal = [0, 0, 0]
            normal[axis] = s
            a, b, c = (corners[q] for q in quad[:3])
            u = [b[k] - a[k] for k in range(3)]
            v = [c[k] - a[k] for k in range(3)]
            cr = [u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0]]
            if sum(cr[k] * normal[k] for k in range(3)) < 0:
                quad.reverse()
            faces.append(quad)
    for q in faces:
        tris.append([q[0], q[1], q[2]])
        tris.append([q[0], q[2], q[3]])
    part = {
        "information": {"authors": "BeamNG x Los Santos", "name": "Traffic proxy body (invisible)"},
        "slotType": "main",
        "variables": [
            ["name", "type", "unit", "category", "default", "min", "max", "title", "description"],
            ["$length", "range", "m", "beamls", medium["length"], 1.0, 20.0, "Length", "Box length"],
            ["$width", "range", "m", "beamls", medium["width"], 0.5, 4.0, "Width", "Box width"],
            ["$height", "range", "m", "beamls", medium["height"], 0.5, 5.0, "Height", "Box height"],
            ["$mass", "range", "kg", "beamls", medium["mass_kg"], 50, 30000, "Mass", "Total mass"],
        ],
        "refNodes": [["ref:", "back:", "left:", "up:"], ["p0", "pb", "pl", "pu"]],
        "nodes": nodes,
        "beams": beams,
        "triangles": tris,
    }
    jbeam = {"beamls_proxy_body": part}
    header = "// GENERATED by tools/gen.py from sheets/traffic_proxies.json. Invisible rigid box: no flexbodies.\n"
    write(os.path.join(BNG_MOD, "vehicles", "beamls_proxy", "beamls_proxy.jbeam"), header + json.dumps(jbeam, indent=1) + "\n")
    write(os.path.join(BNG_MOD, "vehicles", "beamls_proxy", "info.json"), json.dumps({
        "Name": "BeamNG x Los Santos traffic proxy", "Brand": "BeamLS", "Type": "Prop", "Author": "BeamNG x Los Santos",
        "default_pc": medium["id"], "Description": "Invisible solid stand-in for a GTA V vehicle. Spawned by the mashup only."}, indent=2) + "\n")

    # Slab: unit cube centred on the origin, key-coloured unlit material so it vanishes in the composite
    # even if it is drawn.
    k = settings["key_color"]
    kc = " ".join(f"{c / 255:.4f}" for c in k)
    v = []
    for z in (-0.5, 0.5):
        for y in (-0.5, 0.5):
            for x in (-0.5, 0.5):
                v.append((x, y, z))
    idx = {p: i for i, p in enumerate(v)}
    quads = [((-0.5, -0.5, -0.5), (-0.5, 0.5, -0.5), (0.5, 0.5, -0.5), (0.5, -0.5, -0.5)),   # bottom
             ((-0.5, -0.5, 0.5), (0.5, -0.5, 0.5), (0.5, 0.5, 0.5), (-0.5, 0.5, 0.5)),       # top
             ((-0.5, -0.5, -0.5), (0.5, -0.5, -0.5), (0.5, -0.5, 0.5), (-0.5, -0.5, 0.5)),   # front
             ((-0.5, 0.5, -0.5), (-0.5, 0.5, 0.5), (0.5, 0.5, 0.5), (0.5, 0.5, -0.5)),       # back
             ((-0.5, -0.5, -0.5), (-0.5, -0.5, 0.5), (-0.5, 0.5, 0.5), (-0.5, 0.5, -0.5)),   # left
             ((0.5, -0.5, -0.5), (0.5, 0.5, -0.5), (0.5, 0.5, 0.5), (0.5, -0.5, 0.5))]       # right
    tri = []
    for q in quads:
        a, b, c, d = (idx[p] for p in q)
        tri += [a, b, c, a, c, d]
    pos = " ".join(f"{x} {y} {z}" for x, y, z in v)
    dae = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/gen.py: unit cube for BeamNG x Los Santos collision slabs -->
<COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1">
  <asset><unit name="meter" meter="1"/><up_axis>Z_UP</up_axis></asset>
  <library_effects><effect id="beamls_key-fx"><profile_COMMON><technique sid="common"><constant><emission><color>{kc} 1</color></emission></constant></technique></profile_COMMON></effect></library_effects>
  <library_materials><material id="beamls_key" name="beamls_key"><instance_effect url="#beamls_key-fx"/></material></library_materials>
  <library_geometries>
    <geometry id="slab-mesh" name="slab">
      <mesh>
        <source id="slab-pos"><float_array id="slab-pos-array" count="{len(v) * 3}">{pos}</float_array>
          <technique_common><accessor source="#slab-pos-array" count="{len(v)}" stride="3"><param name="X" type="float"/><param name="Y" type="float"/><param name="Z" type="float"/></accessor></technique_common></source>
        <vertices id="slab-vtx"><input semantic="POSITION" source="#slab-pos"/></vertices>
        <triangles material="beamls_key" count="{len(tri) // 3}"><input semantic="VERTEX" source="#slab-vtx" offset="0"/><p>{" ".join(str(i) for i in tri)}</p></triangles>
      </mesh>
    </geometry>
  </library_geometries>
  <library_visual_scenes><visual_scene id="Scene"><node id="slab" name="slab"><instance_geometry url="#slab-mesh"><bind_material><technique_common><instance_material symbol="beamls_key" target="#beamls_key"/></technique_common></bind_material></instance_geometry></node></visual_scene></library_visual_scenes>
  <scene><instance_visual_scene url="#Scene"/></scene>
</COLLADA>
"""
    write(os.path.join(BNG_MOD, "art", "shapes", "beamls", "slab.dae"), dae)
    mat = {"beamls_key": {"name": "beamls_key", "mapTo": "beamls_key", "class": "Material", "version": 1.5,
                          "Stages": [{"baseColorFactor": [k[0] / 255, k[1] / 255, k[2] / 255, 1.0],
                                      "emissiveFactor": [k[0] / 255, k[1] / 255, k[2] / 255]}, {}, {}, {}],
                          "castShadows": False, "translucent": False, "materialTag0": "beamls"}}
    write(os.path.join(BNG_MOD, "art", "shapes", "beamls", "main.materials.json"), json.dumps(mat, indent=2) + "\n")


def gen_credits():
    tp = load("third_party")
    lines = ["# Credits\n", "", "BeamNG × Los Santos is a mashup of Grand Theft Auto V Legacy (Rockstar Games) and BeamNG.drive",
             "(BeamNG GmbH). It ships none of either game's files: it reads both from the player's own installs.", "",
             "Built with AI assistance (Claude Code).", "", "| Component | Author | License | Shipped | Used for |", "|---|---|---|---|---|"]
    for r in tp["rows"]:
        lines.append(f"| [{r['name']}]({r['url']}) {r['version']} | {r['author']} | {r['license']} | {'yes' if r['shipped'] else 'no'} | {r['use']} |")
    lines.append("")
    lines.append("<!-- GENERATED by tools/gen.py from sheets/third_party.json -->")
    write(os.path.join(ROOT, "CREDITS.md"), "\n".join(lines) + "\n")


def main():
    gen_natives()
    gen_protocol()
    gen_settings()
    gen_bngapi()
    gen_tables()
    gen_bng_assets()
    gen_credits()
    d = digest()
    write(os.path.join(GTA_GEN, "STAMP"), d + "\n")
    write(os.path.join(BNG_GEN, "STAMP"), d + "\n")
    print("generated from sheets", d[:12])


if __name__ == "__main__":
    main()
